var iconDictionary={
    "icon-add": "新增(推荐图标)，添加，添加排班，添加专家",
    "icon-write-order": "修改(推荐图标)，录入医嘱",
    "icon-cancel": "删除(推荐图标)",
    "icon-close": "关闭",
    "icon-find": "查询",
    "icon-edit": "医嘱字典库录入",
    "icon-update": "更新",
    "icon-save": "保存（保存诊断）",
    "icon-arrow-down": "上移（位置移动）",
    "icon-arrow-up": "下移（位置移动）",
    "icon-arrow-left": "左移（位置移动）",
    "icon-arrow-right": "右移（位置移动）",
    "icon-back": "回退",
    "icon-blue-edit":"蓝色编辑(可用状态)",
    "icon-gray-edit":"灰色编辑(禁用状态)",
    "icon-pat-write":'群伤患者录入',
    "icon-cal": "计算",
    "icon-card": "卡",
    "icon-clean": "清除",
    "icon-config": "配置",
    "icon-epr": "电子病历",
    "icon-file": "文件",
    "icon-file-open": "打开文件",
    "icon-home": "主页",
    "icon-list": "列表",
    "icon-new": "新建",
    "icon-other": "其它",
    "icon-paper": "文件",
    "icon-plus": "附加",
    "icon-print": "打印(打印汇总单、标签打印)",
    "icon-switch": "交换",
    "icon-import": "导入",
    "icon-export": "导出，，导出待评审",
    "icon-import":"导入",
    "icon-download":"下载",
    "icon-star": "红星",
    "icon-msg": "信息",
    "icon-copy": "复制",
    "icon-stamp": "印章",
    "icon-batch-cfg": "批量配置",
    "icon-inv": "投资",
    "icon-batch-add": "批量添加",
    "icon-eye": "查看，预览",
    "icon-calc": "计算器",
    "icon-submit": "提交",
    "icon-up":"上，向上，上升",
    "icon-down":"下，向下，下降",
    "icon-fx":"函数，生成函数",
    "icon-key":"钥匙，激活，授权",
    "icon-run":"启用，运行，启动，立即执行一次",
    "icon-muti-key":"批量授权",
    "icon-ignore":"忽略",
    "icon-re-ignore":"撤销忽略",
    "icon-unuse":"停用",
    "icon-arrow-up":"全部折叠",
    "icon-gen":"生成",
    "icon-paper-submit":"生成评审报告",
    "icon-open-book":"批量提交审批",
    "icon-export-paper":"导出已评审",
    "icon-track":"追踪",
    "icon-paper-eye":"传阅",
    "icon-compare-no":"未对照",
    "icon-compare-yes":"已对照",
    "icon-compare":"对照",
    "icon-paper-arrow":"退号",
    "icon-paper-upgrade":"把选中属性升级为共有属性",
    "icon-paper-upgrade-add":"把选中属性升级为术语",
    "icon-contain":"包含",
    "icon-paper-save":"保存到模板",
    "icon-virus":"细菌，病原学相关",
    "icon-face-red":"不良反应",
    "icon-list-word":"查询列表",
    "icon-mtpaper-arrw-lftp":"撤销执行多条",
    "icon-tube":"成分含量",
    "icon-radio":"单选",
    "icon-durg-ref":"当前联用药品",
    "icon-dsh-water":"滴速",
    "icon-nail":"钉子",
    "icon-location":"定位",
    "icon-upload":"上传",
    "icon-mttext":"多行文本",
    "icon-check":"多选",
    "icon-translate-word":"翻译",
    "icon-analysis":"分析",
    "icon-close-word":"封闭，关闭",
    "icon-paper-drug":"辅助用药个数，特抗药指征",
    "icon-complex":"复合查询",
    "icon-mtpaper-add":"复制并增加",
    "icon-mtpaper-undo":"复制选中属性到本术语",
    "icon-mtpaper-redo":"复制选中属性到其他术语",
    "icon-format-line":"配置，更多",
    "icon-format-line-dott":"格式行，点",
    "icon-format-line-num":"格式行，数字",
    "icon-double-quotes":"引用，双引号",
    "icon-allergy-word":"过敏记录",
    "icon-public-word":"公有",
    "icon-icd":"诊断ICD",
    "icon-base-word":"基本查询",
    "icon-text-word":"文本，文本编辑",
    "icon-tip-blue":"提示",
    "icon-all-screen":"扩展，全屏",
    "icon-unlock":"解锁",
    "icon-alert-red":"注意事项",
    "icon-switch":"切换",
    "icon-top-green":"上移",
    "icon-checkbox":"检验检查勾选",
    "icon-base-info":"基本信息",
    "icon-arrow-zoom":"放大，扩展",
    "icon-down-arrow-box":"下拉框",
    "icon-paper-bed":"临床意义",
    "icon-blue-move":"位置移动",
    "icon-mutpaper-x":"作废多条",
    "icon-paper-blue-line":"使用目的",
    "icon-paper-chart":"使用频次",
    "icon-no-conatin":"例外",
    "icon-ref":"关联",
    "icon-other-yellow":"其他",
    "icon-doctor-green-no":"删除医生权限",
    "icon-pat-alert-red":"危重患者",
    "icon-clock-record":"历史记录",
    "icon-cancel-ref":"取消关联,拆关联",
    "icon-cancel-top":"取消置顶",
    "icon-blue-drug-ok":"可配伍药品",
    "icon-adm-same":"同义诊断",
    "icon-right-arrow":"向右折叠",
    "icon-clock":"回顾",
    "icon-pat-house":"在院患者",
    "icon-adm-add":"增加诊断",
    "icon-audit-x":"审核不通过",
    "icon-arrow-blue":"小图标",
    "icon-pat-opr":"手术患者",
    "icon-paper-opr-record":"手术记录",
    "icon-mutpaper-tri":"执行多条",
    "icon-drug-audit":"抗生素审核",
    "icon-virus-drug":"抗菌处方权",
    "icon-green-chart":"推荐检查方案",
    "icon-injector":"推荐治疗方案",
    "icon-drug":"推荐用药方案",
    "icon-paper-table":"推荐评估表",
    "icon-text":"文本",
    "icon-paper-new":"新建,新建方子",
    "icon-clock-blod":"时间,时钟",
    "icon-chg-doctor-grant":"更改医生权限",
    "icon-cal-pen":"注册知识点映射",
    "icon-water-drop":"浓度",
    "icon-pat-add-red":"添加参与人",
    "icon-paper-x":"清除方子",
    "icon-yellow-qa":"溶媒量",
    "icon-fire":"炮制作用",
    "icon-gen-barcode":"生成检索码",
    "icon-bottle-drug":"用法用量",
    "icon-book-green":"相关文献",
    "icon-knw-submit":"知识提交",
    "icon-paper-no":"禁忌症",
    "icon-private-word":"私有",
    "icon-move-left-most":"移到最前",
    "icon-drug-arrow-red":"给药途径",
    "icon-durg-freq":"给药频率",
    "icon-move-up-most":"置顶",
    "icon-drug-link":"联合用药",
    "icon-paper-link-pen":"联用变更原因",
    "icon-tel":"联系方式",
    "icon-trans-pat":"转出患者",
    "icon-paper-ok":"适应症",
    "icon-repeat-drug":"重复用药",
    "icon-find-adm":"鉴别诊断",
    "icon-lock":"锁死",
    "icon-drug-clock":"预防用药时间控制",
    "icon-down-blue":"下移，向下",
    "icon-add-report":"增加补充报告",
    "icon-export-report":"导出报告，导出模板",
    "icon-paper-plane":"纸飞机，发布",
    'icon-undo-paper-plane':"撤销发布",
    'icon-h24-stat':"24小时统计",
    'icon-stat':"按时间段统计",
    'icon-paper-pen':"日间小结",
    "icon-w-rent": "租用单",
    "icon-w-run": "执行计划",
    "icon-w-line-key": "论证",
    "icon-w-takes": "接送单",
    "icon-w-key":'授权，钥匙',
    "icon-w-img":'图片信息',
    "icon-w-setting":"附属设备，设备，设置",
    "icon-w-add":"新增（推荐图标），添加，添加排班",
    "icon-w-close":"关闭",
    "icon-w-find":"查找",
    "icon-w-edit":"医嘱字典库录入",
    "icon-w-update":"更新",
    "icon-w-save":"保存（保存诊断）",
    "icon-w-arrow-down":"向下箭头，向下展开",
    "icon-w-arrow-up":"向上箭头，向上折叠",
    "icon-w-arrow-left":"向左箭头，向左折叠",
    "icon-w-arrow-right":"向右箭头，向右展开",
    "icon-w-back":"回退",
    "icon-w-cal":"计算",
    "icon-w-cancel":"取消",
    "icon-w-card":"卡片",
    "icon-w-clean":"清除",
    "icon-w-config":"配置",
    "icon-w-epr":"电子病历",
    "icon-w-file":"文件",
    "icon-w-file-open":"打开文件",
    "icon-w-home":"主页",
    "icon-w-list":"列表",
    "icon-w-new":"新建",
    "icon-w-other":"其他",
    "icon-w-paper":"文档",
    "icon-w-plus":"附加",
    "icon-w-print":"打印",
    "icon-w-switch":"交换",
    "icon-w-import":"导入",
    "icon-w-export":"导出",
    "icon-w-star":"星",
    "icon-w-msg":"信息",
    "icon-w-copy":"复制",
    "icon-w-stamp":"印章",
    "icon-w-batch-cfg":"批量配置",
    "icon-w-inv":"投资",
    "icon-w-batch-add":"批量增加",
    "icon-w-eye":"查看，预览",
    "icon-w-calc":"计算器",
    "icon-w-submit":"提交",
    "icon-w-clock":"时钟",
    "icon-w-rent":"租金",
    "icon-w-ok":"完成",
    "icon-w-filter":"过滤",
    "icon-w-predrug":"备药",
    "icon-w-trigger-box":"触发",
    "icon-remove": "删除",
    "icon-cut": "剪切",
    "icon-ok": "通行",
    "icon-no": "禁止",
    "icon-reload": "刷新",
    "icon-search": "查询",
    "icon-help": "帮助",
    "icon-sum": "求和",
    "icon-tip": "提示",
    "icon-filter": "过滤",
    "icon-bed": "床位",
    "icon-house": "主页，本科室",
    "icon-person": "人员，用户",
    "icon-patient": "病人",
    "icon-outhosp-patient": "出院病人",
    "icon-stethoscope": "诊断",
    "icon-uncheckin": "未登记",
    "icon-checkin": "登记",
    "icon-end-adm": "完成接诊",
    "icon-change-loc": "转科",
    "icon-doctor": "医生",
    "icon-clear-screen": "清屏",
    "icon-read-card": "读卡",
    "icon-upload-cloud": "上传",
    "icon-unload-cloud": "下载",
    "icon-reset": "重置",
    "icon-patient-info": "病人信息",
    "icon-del-diag": "删除诊断",
    "icon-add-diag": "增加诊断",
    "icon-emr-cri": "病程",
    "icon-funnel-eye": "完成可查看",
    "icon-funnel-half": "进程中",
    "icon-funnel-empty": "开始等待",
    "icon-omega": "特殊符号",
    "icon-fee-arrow": "缴费",
    "icon-fee": "费用",
    "icon-inpatient": "住院病人，住院部",
    "icon-outpatient": "门诊病人，门诊部",
    "icon-emergency": "紧急情况",
    "icon-star-yellow": "黄星",
    "icon-star-light-yellow": "浅黄星",
    "icon-star-half": "半空星",
    "icon-star-empty": "空星",
    "icon-book": "预约",
    "icon-all-select": "全选，全部选择",
    "icon-all-unselect":"全不选，取消全选",
    "icon-select-grant": "授予选择权限",
    "icon-cancel-select-grant": "取消授予的选择权限",
    "icon-refuse-select-grant": "拒绝选择权限的授予",
    "icon-double-quotes": "双引号",
    "icon-transfer": "交换，转换",
    "icon-import-xls": "导入xls工作表",
    "icon-init": "初始化",
    "icon-inv-search": "投资搜索，投资查询",
    "icon-chart-sum": "图表中求和",
    "icon-chart-year": "年图表信息",
    "icon-attachment": "附件",
    "icon-import-reset": "导入重置的信息",
    "icon-mnypaper-cfg": "纸币配置",
    "icon-mnypaper-run": "纸币经营",
    "icon-mnypaper-ok": "纸币通行",
    "icon-mnypaper-no": "纸币禁止",
    "icon-mnypaper-down": "纸币下发",
    "icon-mnypaper-down2": "纸币下发",
    "icon-stamp-cancel": "印章的取消",
    "icon-stamp-pass": "印章的通过",
    "icon-line-paid": "支付方式，支付途径",
    "icon-split": "分开，向两边分开",
    "icon-alert": "警告",
    "icon-user": "用户",
    "icon-money-down": "资金下发",
    "icon-max-no": "向两边扩展至最大",
    "icon-excel": "excel工作表格",
    "icon-img": "图片信息，产品图片",
    "icon-save-to": "保存，保存到",
    "icon-save-sure": "确认保存",
    "icon-export-data": "导出当前页",
    "icon-export-all": "导出全部",
    "icon-set-col": "列设置",
    "icon-template": "模板",
    "icon-adjust-inventory": "盘点调整",
    "icon-cancel-money": "取消实盘完成",
    "icon-set-zero": "设置未填数等于0",
    "icon-accept-money": "实盘完成",
    "icon-accept": "通过（接受）",
    "icon-show-set": "显示设置",
    "icon-abort-order": "中止预约",
    "icon-camera":"拍照,照相机",
    "icon-cancel-order": "取消预约",
    "icon-copy-drug": "复制药物，重复同样的药品",
    "icon-copy-prn": "长期备用医嘱",
    "icon-copy-sos": "临时备用医嘱",
    "icon-exe-order": "执行订单",
    "icon-replace-order": "替换订单",
    "icon-stop-order": "停止预约",
    "icon-add-note": "增加注意事项",
    "icon-apply-adm": "申请接诊",
    "icon-apply-check": "申请核查",
    "icon-apply-opr": "申请手术",
    "icon-check-reg": "核对登记",
    "icon-paper-cfg": "文档配置，文档匹配",
    "icon-paper-tri": "文档上向右的三角箭头，执行文档",
    "icon-resort": "应急对策",
    "icon-save-tmpl": "保存模板",
    "icon-paper-stamp": "在文件中盖章",
    "icon-paper-money": "纸币",
    "icon-paper-arrow-down": "箭头向下",
    "icon-paper-arrow-up": "箭头向上，病例上传，文档上传",
    "icon-paper-link": "病例上的关联性，文档间的相关联",
    "icon-paper-info": "材料信息，文档信息",
    "icon-set-paper": "设置未填数等于帐盘数",
    "icon-lt-rt-37": "37分布局",
    "icon-lt-rt-55": "对半分布局",
    "icon-lt-rt-73": "73分布局",
    "icon-lt-rt-19": "19分布局",
    "icon-bold": "加粗",
    "icon-font": "字体",
    "icon-strikethrough": "划横线",
    "icon-underline": "加下划线",
    "icon-incline": "斜体",
    "icon-subscript": "下标",
    "icon-superscript": "上标",
    "icon-indentation": "缩进",
    "icon-unindent": "未缩进",
    "icon-align-justify": "两端对齐",
    "icon-align-left": "左对齐",
    "icon-align-center": "居中",
    "icon-align-right": "右对齐",
    "icon-cut-blue": "剪切",
    "icon-paste": "粘贴",
    "icon-paste-board": "粘贴板",
    "icon-arrow-left-top": "撤销（撤销执行）",
    "icon-arrow-right-top": "箭头",
    "icon-arrow-top": "上移（位置移动）",
    "icon-arrow-bottom": "下移（位置移动）",
    "icon-undo": "箭头",
    "icon-redo": "箭头",
    "icon-pause":"暂停，停止",
    "icon-forbid":"禁用，禁止，配伍禁忌",
    "icon-make-oppointment":"约，预约",
    "icon-scanning":"扫描",
    "icon-slide-return":"归还",
    "icon-doc-caseload":"医生工作量",
    "icon-snowflake-blue":"冰冻及时率",
    "icon-print-box":"打印包埋盒",
    "icon-tube-del":"删除标本",
    "icon-tube-add":"添加标本",
    "icon-wrench-blue":"处理措施",
    "icon-big-open-file":"资料归档，文件打开",
    "icon-big-waxblock-return":"蜡块归档",
    "icon-big-cells-smear":"细胞学涂片",
    "icon-big-slide-add":"新建借片",
    "icon-big-slide-filed":"玻片归档",
    "icon-big-slide-return":"玻片归还",
    "icon-big-slide-send":"玻片发派，派片",
    "icon-big-slide-made":"制片",
    "icon-big-dyeing":"染色",
    "icon-big-chart-paper":"技术医嘱",
    "icon-big-embed":"包埋处理",
    "icon-big-print-box":"包埋盒打印",
    "icon-big-save-next":"保存&下例",
    "icon-big-save-add":"保存&新建",
    "icon-big-book-yellow":"补充报告",
    "icon-big-pre":"上一个，上一页",
    "icon-big-next":"下一个，下一页",
    "icon-big-med-bag":"随访，医疗包",
    "icon-big-doctor-green": "医生绿色通道，急诊绿色通道",
    "icon-big-doctor-adm": "医生接诊，医疗管理",
    "icon-big-favorite": "收藏",
    "icon-big-favorite-add": "增加收藏",
    "icon-big-img": "图片信息",
    "icon-big-omega": "特殊符号",
    "icon-big-position": "定位",
    "icon-big-print": "打印",
    "icon-big-refresh": "刷新",
    "icon-big-unlock": "解锁",
    "icon-big-book-arrow": "返回就诊信息，返回病例信息情况",
    "icon-big-book-eye": "查看病历，查看文档",
    "icon-big-book-ref": "引用文档",
    "icon-big-book-arrow-rt": "下发文档，下发病例本",
    "icon-big-book-to-book": "转换，转换病例",
    "icon-big-del": "删除",
    "icon-big-save": "保存",
    "icon-big-clear": "清除",
    "icon-big-ring-blue": "蓝色预警广播",
    "icon-big-ring": "橙色预警广播",
    "icon-big-skip-no": "跳页，跳过当前页",
    "icon-big-paper-search": "信息搜索，病例查询",
    "icon-big-paper-pen": "修改，医嘱录入",
    "icon-big-paper-arrow": "上交文档，上缴材料",
    "icon-big-fee-arrow": "费用，缴费",
    "icon-big-card-reader": "读卡器",
    "icon-big-home": "主页",
    "icon-big-stamp": "印记，盖章",
    "icon-big-tooth": "牙齿",
    "icon-big-open-eye": "打开预览",
    "icon-big-close-eye": "关闭预览",
    "icon-big-stop": "禁止，禁止通行",
    "icon-big-start": "开始，从当前位置继续",
    "icon-big-return": "返回",
    "icon-big-meterage": "测量，数据比较",
    "icon-big-maint": "维护，维修",
    "icon-big-inspect": "医生检查",
    "icon-big-disuse": "弃用，废弃物",
    "icon-big-change-account": "账单修改，账单记录",
    "icon-big-card": "卡，医疗卡",
    "icon-big-bar": "扫描",
    "icon-big-lt-rt-37": "37分布局",
    "icon-big-lt-rt-55": "对半分布局",
    "icon-big-lt-rt-73": "73分布局",
    "icon-big-lt-rt-19": "19分布局",
    "icon-big-delete-col": "删除列",
    "icon-big-delete-row": "删除行",
    "icon-big-delete-table": "删除表格",
    "icon-big-insert-col": "插入列",
    "icon-big-insert-row": "插入行",
    "icon-big-insert-table": "插入表格",
    "icon-big-split-cells": "缩小间距，划分单元格",
    "icon-big-help": "帮助",
    "icon-big-paper": "文件，文档",
    "icon-big-question": "问题提问",
    "icon-big-tip":"暂无回复,提示",
    "icon-big-rad":"放射",
    "icon-big-balance":"天平,称重",
    "icon-big-print-run":"自动续打，打印，连续打印",
    "icon-big-paper-time":"报表展示",
    "icon-big-alert-yellow":"指标预警",
    "icon-big-pre-audit":"专家审标",
    "icon-big-paper-gray":"未达标指标",
    "icon-big-msg":"报告提醒",
    "icon-big-equi-cfg":"设备属性维护，设备维护",
    "icon-big-med-equi":"医疗设备特殊设备，医疗设备",
    "icon-big-alert":"特殊设备，警告"
};